import { buildPortfolioProject } from "./portfolio-helpers";
import type { PortfolioProjectInput } from "./portfolio-helpers";
import type { Project } from "./types";

/**
 * Portfolio projects extracted from MisrConsult Company Portfolio PDF (2026).
 * Fields marked with TODO in comments require manual verification.
 */
export const PORTFOLIO_INPUTS: PortfolioProjectInput[] = [
  // ── LOCAL PROJECTS (Egypt) ──────────────────────────────────────────────
  {
    slug: "phd-new-capital-village-r4",
    title: "PHD — New Capital Village R4",
    categoryId: "residential",
    location: "New Administrative Capital, Egypt",
    area: "1,218,013 m²",
    scope: "Full Design Package",
  },
  {
    slug: "97-hills",
    title: "97 Hills",
    categoryId: "residential",
    location: "Cairo, Egypt",
    area: "407,400 m²",
    scope: "Full Design Package",
  },
  {
    slug: "palm-hills-new-cairo",
    title: "Palm Hills New Cairo",
    categoryId: "residential",
    location: "New Cairo, Egypt",
    area: "1,700,000 m²",
    scope: "Full Design Package",
    client: "Palm Hills",
  },
  {
    slug: "capital-gardens-new-cairo",
    title: "Capital Gardens New Cairo",
    categoryId: "residential",
    location: "New Cairo, Egypt",
    area: "518,707 m²",
    scope: "Full Design Package",
  },
  {
    slug: "emaar-marassi-red-sea",
    title: "Emaar Marassi Red Sea",
    categoryId: "residential",
    location: "Red Sea, Egypt",
    // TODO: PDF lists both 5,711 m² (design package) and 2,023,430 m² (buildings) — verify correct primary area
    area: "2,023,430 m²",
    scope: "Full Design Package",
    client: "EMAAR",
  },
  {
    slug: "fifth-settlement-full-design",
    // TODO: PDF slide does not state a clear project name — verify official title
    title: "5th Settlement Development",
    categoryId: "residential",
    location: "5th Settlement, Cairo, Egypt",
    area: "420,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "mivida-gardens",
    title: "Mivida Gardens",
    categoryId: "residential",
    location: "5th Settlement, Cairo, Egypt",
    // TODO: PDF shows "???" for one area field — using 420,000 m² from portfolio slide
    area: "420,000 m²",
    scope: "Full Design Package",
    client: "EMAAR",
  },
  {
    slug: "mivida",
    title: "Mivida",
    categoryId: "residential",
    location: "Cairo, Egypt",
    area: "3,500,000 m²",
    scope: "Buildings & Infrastructure",
    client: "EMAAR",
  },
  {
    slug: "mivida-lake",
    title: "Mivida Lake",
    categoryId: "infrastructure",
    location: "Cairo, Egypt",
    area: "71,200 m²",
    scope: "MEP & Lake Infrastructure",
    client: "EMAAR",
  },
  {
    slug: "al-burouj",
    title: "Al Burouj",
    categoryId: "residential",
    location: "Al-Shorouk, Egypt",
    area: "17,640,195 m²",
    scope: "Full Design Package",
  },
  {
    slug: "zed-east",
    title: "Zed East",
    categoryId: "residential",
    location: "5th Settlement, Cairo, Egypt",
    area: "156,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "sarai-1",
    title: "Sarai — Phase 1",
    categoryId: "residential",
    location: "New Cairo, Egypt",
    area: "210,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "sarai-2-midanat-masr",
    title: "Sarai — Phase 2 / Midanat Masr",
    categoryId: "residential",
    location: "New Cairo, Egypt",
    // TODO: PDF lists both 50 Fed. and 135 Fed. — verify phase breakdown
    area: "210,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "sarai-cavana",
    title: "Sarai Cavana",
    categoryId: "residential",
    location: "New Cairo, Egypt",
    area: "239,400 m²",
    scope: "Full Design Package",
  },
  {
    slug: "mmhd-sarai-assuit",
    title: "MMHD Sarai Assuit",
    categoryId: "residential",
    location: "Assiut, Egypt",
    area: "3,500,000 m²",
    scope: "Buildings",
  },
  {
    slug: "arado-headquarters",
    title: "Arado Headquarters",
    categoryId: "commercial",
    location: "Cairo, Egypt",
    area: "12,000 m²",
    scope: "MEP Package",
  },
  {
    slug: "auc-new-campus",
    title: "AUC New Campus",
    categoryId: "educational",
    location: "Cairo, Egypt",
    area: "1,000,000 m²",
    scope: "Infrastructure",
  },
  {
    slug: "tmg-four-seasons",
    title: "TMG Four Seasons",
    categoryId: "hotels",
    location: "Cairo, Egypt",
    area: "141,640 m²",
    scope: "MEP Package",
    client: "TMG",
  },

  // ── INTERNATIONAL PROJECTS ────────────────────────────────────────────────
  {
    slug: "king-faisal-university-hospital",
    title: "King Faisal University Hospital",
    categoryId: "healthcare",
    location: "Kingdom of Saudi Arabia",
    area: "13,780 m²",
    scope: "Full Design Package",
  },
  {
    slug: "prince-mohamed-bin-fahd-medical-research",
    title: "Prince Mohamed Bin Fahd Center for Medical Research",
    categoryId: "healthcare",
    location: "Dammam, Saudi Arabia",
    area: "107,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "tabouk-hotel",
    title: "Tabouk Hotel",
    categoryId: "hotels",
    location: "Tabouk, Saudi Arabia",
    area: "101,726 m²",
    scope: "Full Design Package",
  },
  {
    slug: "baha-hotel",
    title: "Baha Hotel",
    categoryId: "hotels",
    location: "Al Baha, Saudi Arabia",
    area: "103,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "labor-camp",
    title: "Labor Camp",
    categoryId: "industrial",
    location: "Kingdom of Saudi Arabia",
    area: "500,000 m²",
    scope: "Full Design Package",
    // TODO: Verify whether this is industrial or residential worker housing
  },
  {
    slug: "al-khafji-joint-operations-housing",
    title: "Al-Khafji Joint Operations Housing Area",
    categoryId: "residential",
    location: "Al-Khafji, Saudi Arabia",
    // TODO: PDF shows 1,400,000 KM² — likely a typo for m²
    area: "1,400,000 m²",
    scope: "Full Design Package",
  },
  {
    slug: "king-faisal-university",
    title: "King Faisal University",
    categoryId: "educational",
    location: "Kingdom of Saudi Arabia",
    area: "570,000 m²",
    scope: "Buildings & Landscape",
  },
  {
    slug: "qassim-university-hospital",
    title: "Qassim University Hospital",
    categoryId: "healthcare",
    location: "Qassim, Saudi Arabia",
    area: "140,000 m²",
    scope: "Buildings",
  },
  {
    slug: "gotevt-headquarters",
    title: "General Organization for Technical Education & Vocational Training Headquarters",
    categoryId: "educational",
    location: "Kingdom of Saudi Arabia",
    area: "36,850 m²",
    scope: "Buildings",
  },
  {
    slug: "jubail-university-college",
    title: "Jubail University College",
    categoryId: "educational",
    location: "Jubail, Saudi Arabia",
    area: "150,000 m²",
    scope: "Buildings",
  },
  {
    slug: "arriyadh-courts-complex",
    title: "Arriyadh Courts Complex",
    categoryId: "commercial",
    location: "Riyadh, Saudi Arabia",
    area: "80,000 m²",
    scope: "Buildings",
  },
  {
    slug: "wakf-al-madani-hotel",
    title: "Wakf Al Madani Hotel — Haram El Madinah Central Zone",
    categoryId: "hotels",
    location: "Madinah, Saudi Arabia",
    area: "8,600 m²",
    scope: "Buildings",
  },
  {
    slug: "jubail-industrial-college",
    title: "Jubail Industrial College",
    categoryId: "industrial",
    location: "Jubail, Saudi Arabia",
    area: "48,588 m²",
    scope: "Buildings",
    // TODO: Verify category — may also fit Educational Facilities
  },
  {
    slug: "egyptian-consulate-jeddah",
    title: "Egyptian Consulate in Jeddah",
    categoryId: "commercial",
    location: "Jeddah, Saudi Arabia",
    area: "6,300 m²",
    scope: "MEP Package",
  },
  {
    slug: "ebda-khaira",
    title: "Ebda & Khaira",
    categoryId: "infrastructure",
    location: "Kingdom of Saudi Arabia",
    area: "48,010 m²",
    scope: "Infrastructure Design",
  },
  {
    slug: "jeddah-wastewater-networks",
    title: "Jeddah Wastewater Networks — Phase 1, Contract 7",
    categoryId: "infrastructure",
    location: "Jeddah, Saudi Arabia",
    area: "18,860,000 m²",
    scope: "Tender Documents of Wastewater Networks",
  },
  {
    slug: "iskan-al-ahsa",
    title: "Iskan Al-Ahsa",
    categoryId: "infrastructure",
    location: "Al-Ahsa, Saudi Arabia",
    area: "5,463,256 m²",
    scope: "Infrastructure",
  },
  {
    slug: "dubai-business-bay",
    title: "Dubai Business Bay",
    categoryId: "mixed-use",
    location: "Dubai, UAE",
    area: "4,460,000 m²",
    scope: "Infrastructure Design",
  },
  {
    slug: "ebb-university-yemen",
    title: "EBB University",
    categoryId: "educational",
    location: "Yemen",
    area: "800,000 m²",
    scope: "Infrastructure Design",
  },
  {
    slug: "lusail",
    title: "Lusail",
    categoryId: "mixed-use",
    location: "Lusail, Qatar",
    area: "2,187,791 m²",
    scope: "Infrastructure Design",
  },
  {
    slug: "damam-water-tower",
    title: "Dammam Water Tower",
    categoryId: "infrastructure",
    location: "Dammam, Saudi Arabia",
    area: "12,876 m²",
    scope: "Structure & MEP Package",
    // TODO: PDF slide contains garbled text — verify project details
  },
];

export const portfolioProjects: Project[] = PORTFOLIO_INPUTS.map(buildPortfolioProject);
