// Auto-generated by scripts/generate-portfolio-projects.mjs — do not edit manually

export { phdNewCapitalVillageR4 } from "./phd-new-capital-village-r4";
export { n97Hills } from "./97-hills";
export { palmHillsNewCairo } from "./palm-hills-new-cairo";
export { capitalGardensNewCairo } from "./capital-gardens-new-cairo";
export { emaarMarassiRedSea } from "./emaar-marassi-red-sea";
export { fifthSettlementFullDesign } from "./fifth-settlement-full-design";
export { mividaGardens } from "./mivida-gardens";
export { mivida } from "./mivida";
export { mividaLake } from "./mivida-lake";
export { alBurouj } from "./al-burouj";
export { zedEast } from "./zed-east";
export { sarain1 } from "./sarai-1";
export { sarain2MidanatMasr } from "./sarai-2-midanat-masr";
export { saraiCavana } from "./sarai-cavana";
export { mmhdSaraiAssuit } from "./mmhd-sarai-assuit";
export { aradoHeadquarters } from "./arado-headquarters";
export { aucNewCampus } from "./auc-new-campus";
export { tmgFourSeasons } from "./tmg-four-seasons";
export { kingFaisalUniversityHospital } from "./king-faisal-university-hospital";
export { princeMohamedBinFahdMedicalResearch } from "./prince-mohamed-bin-fahd-medical-research";
export { taboukHotel } from "./tabouk-hotel";
export { bahaHotel } from "./baha-hotel";
export { laborCamp } from "./labor-camp";
export { alKhafjiJointOperationsHousing } from "./al-khafji-joint-operations-housing";
export { kingFaisalUniversity } from "./king-faisal-university";
export { qassimUniversityHospital } from "./qassim-university-hospital";
export { gotevtHeadquarters } from "./gotevt-headquarters";
export { jubailUniversityCollege } from "./jubail-university-college";
export { arriyadhCourtsComplex } from "./arriyadh-courts-complex";
export { wakfAlMadaniHotel } from "./wakf-al-madani-hotel";
export { jubailIndustrialCollege } from "./jubail-industrial-college";
export { egyptianConsulateJeddah } from "./egyptian-consulate-jeddah";
export { ebdaKhaira } from "./ebda-khaira";
export { jeddahWastewaterNetworks } from "./jeddah-wastewater-networks";
export { iskanAlAhsa } from "./iskan-al-ahsa";
export { dubaiBusinessBay } from "./dubai-business-bay";
export { ebbUniversityYemen } from "./ebb-university-yemen";
export { lusail } from "./lusail";
export { damamWaterTower } from "./damam-water-tower";

import type { Project } from "./types";
import { phdNewCapitalVillageR4 } from "./phd-new-capital-village-r4";
import { n97Hills } from "./97-hills";
import { palmHillsNewCairo } from "./palm-hills-new-cairo";
import { capitalGardensNewCairo } from "./capital-gardens-new-cairo";
import { emaarMarassiRedSea } from "./emaar-marassi-red-sea";
import { fifthSettlementFullDesign } from "./fifth-settlement-full-design";
import { mividaGardens } from "./mivida-gardens";
import { mivida } from "./mivida";
import { mividaLake } from "./mivida-lake";
import { alBurouj } from "./al-burouj";
import { zedEast } from "./zed-east";
import { sarain1 } from "./sarai-1";
import { sarain2MidanatMasr } from "./sarai-2-midanat-masr";
import { saraiCavana } from "./sarai-cavana";
import { mmhdSaraiAssuit } from "./mmhd-sarai-assuit";
import { aradoHeadquarters } from "./arado-headquarters";
import { aucNewCampus } from "./auc-new-campus";
import { tmgFourSeasons } from "./tmg-four-seasons";
import { kingFaisalUniversityHospital } from "./king-faisal-university-hospital";
import { princeMohamedBinFahdMedicalResearch } from "./prince-mohamed-bin-fahd-medical-research";
import { taboukHotel } from "./tabouk-hotel";
import { bahaHotel } from "./baha-hotel";
import { laborCamp } from "./labor-camp";
import { alKhafjiJointOperationsHousing } from "./al-khafji-joint-operations-housing";
import { kingFaisalUniversity } from "./king-faisal-university";
import { qassimUniversityHospital } from "./qassim-university-hospital";
import { gotevtHeadquarters } from "./gotevt-headquarters";
import { jubailUniversityCollege } from "./jubail-university-college";
import { arriyadhCourtsComplex } from "./arriyadh-courts-complex";
import { wakfAlMadaniHotel } from "./wakf-al-madani-hotel";
import { jubailIndustrialCollege } from "./jubail-industrial-college";
import { egyptianConsulateJeddah } from "./egyptian-consulate-jeddah";
import { ebdaKhaira } from "./ebda-khaira";
import { jeddahWastewaterNetworks } from "./jeddah-wastewater-networks";
import { iskanAlAhsa } from "./iskan-al-ahsa";
import { dubaiBusinessBay } from "./dubai-business-bay";
import { ebbUniversityYemen } from "./ebb-university-yemen";
import { lusail } from "./lusail";
import { damamWaterTower } from "./damam-water-tower";

export const portfolioProjectList: Project[] = [
  phdNewCapitalVillageR4,
  n97Hills,
  palmHillsNewCairo,
  capitalGardensNewCairo,
  emaarMarassiRedSea,
  fifthSettlementFullDesign,
  mividaGardens,
  mivida,
  mividaLake,
  alBurouj,
  zedEast,
  sarain1,
  sarain2MidanatMasr,
  saraiCavana,
  mmhdSaraiAssuit,
  aradoHeadquarters,
  aucNewCampus,
  tmgFourSeasons,
  kingFaisalUniversityHospital,
  princeMohamedBinFahdMedicalResearch,
  taboukHotel,
  bahaHotel,
  laborCamp,
  alKhafjiJointOperationsHousing,
  kingFaisalUniversity,
  qassimUniversityHospital,
  gotevtHeadquarters,
  jubailUniversityCollege,
  arriyadhCourtsComplex,
  wakfAlMadaniHotel,
  jubailIndustrialCollege,
  egyptianConsulateJeddah,
  ebdaKhaira,
  jeddahWastewaterNetworks,
  iskanAlAhsa,
  dubaiBusinessBay,
  ebbUniversityYemen,
  lusail,
  damamWaterTower,
];
