// Auto-generated by scripts/generate-portfolio-projects.mjs — do not edit manually
import type { ComponentType } from "react";
import type { Project } from "@/lib/projects";
import { PhdNewCapitalVillageR4PageContent } from "./phd-new-capital-village-r4/page-content";
import { N97HillsPageContent } from "./97-hills/page-content";
import { PalmHillsNewCairoPageContent } from "./palm-hills-new-cairo/page-content";
import { CapitalGardensNewCairoPageContent } from "./capital-gardens-new-cairo/page-content";
import { EmaarMarassiRedSeaPageContent } from "./emaar-marassi-red-sea/page-content";
import { FifthSettlementFullDesignPageContent } from "./fifth-settlement-full-design/page-content";
import { MividaGardensPageContent } from "./mivida-gardens/page-content";
import { MividaPageContent } from "./mivida/page-content";
import { MividaLakePageContent } from "./mivida-lake/page-content";
import { AlBuroujPageContent } from "./al-burouj/page-content";
import { ZedEastPageContent } from "./zed-east/page-content";
import { Sarain1PageContent } from "./sarai-1/page-content";
import { Sarain2MidanatMasrPageContent } from "./sarai-2-midanat-masr/page-content";
import { SaraiCavanaPageContent } from "./sarai-cavana/page-content";
import { MmhdSaraiAssuitPageContent } from "./mmhd-sarai-assuit/page-content";
import { AradoHeadquartersPageContent } from "./arado-headquarters/page-content";
import { AucNewCampusPageContent } from "./auc-new-campus/page-content";
import { TmgFourSeasonsPageContent } from "./tmg-four-seasons/page-content";
import { KingFaisalUniversityHospitalPageContent } from "./king-faisal-university-hospital/page-content";
import { PrinceMohamedBinFahdMedicalResearchPageContent } from "./prince-mohamed-bin-fahd-medical-research/page-content";
import { TaboukHotelPageContent } from "./tabouk-hotel/page-content";
import { BahaHotelPageContent } from "./baha-hotel/page-content";
import { LaborCampPageContent } from "./labor-camp/page-content";
import { AlKhafjiJointOperationsHousingPageContent } from "./al-khafji-joint-operations-housing/page-content";
import { KingFaisalUniversityPageContent } from "./king-faisal-university/page-content";
import { QassimUniversityHospitalPageContent } from "./qassim-university-hospital/page-content";
import { GotevtHeadquartersPageContent } from "./gotevt-headquarters/page-content";
import { JubailUniversityCollegePageContent } from "./jubail-university-college/page-content";
import { ArriyadhCourtsComplexPageContent } from "./arriyadh-courts-complex/page-content";
import { WakfAlMadaniHotelPageContent } from "./wakf-al-madani-hotel/page-content";
import { JubailIndustrialCollegePageContent } from "./jubail-industrial-college/page-content";
import { EgyptianConsulateJeddahPageContent } from "./egyptian-consulate-jeddah/page-content";
import { EbdaKhairaPageContent } from "./ebda-khaira/page-content";
import { JeddahWastewaterNetworksPageContent } from "./jeddah-wastewater-networks/page-content";
import { IskanAlAhsaPageContent } from "./iskan-al-ahsa/page-content";
import { DubaiBusinessBayPageContent } from "./dubai-business-bay/page-content";
import { EbbUniversityYemenPageContent } from "./ebb-university-yemen/page-content";
import { LusailPageContent } from "./lusail/page-content";
import { DamamWaterTowerPageContent } from "./damam-water-tower/page-content";

export const portfolioPageContentBySlug = {
  "phd-new-capital-village-r4": PhdNewCapitalVillageR4PageContent,
  "97-hills": N97HillsPageContent,
  "palm-hills-new-cairo": PalmHillsNewCairoPageContent,
  "capital-gardens-new-cairo": CapitalGardensNewCairoPageContent,
  "emaar-marassi-red-sea": EmaarMarassiRedSeaPageContent,
  "fifth-settlement-full-design": FifthSettlementFullDesignPageContent,
  "mivida-gardens": MividaGardensPageContent,
  "mivida": MividaPageContent,
  "mivida-lake": MividaLakePageContent,
  "al-burouj": AlBuroujPageContent,
  "zed-east": ZedEastPageContent,
  "sarai-1": Sarain1PageContent,
  "sarai-2-midanat-masr": Sarain2MidanatMasrPageContent,
  "sarai-cavana": SaraiCavanaPageContent,
  "mmhd-sarai-assuit": MmhdSaraiAssuitPageContent,
  "arado-headquarters": AradoHeadquartersPageContent,
  "auc-new-campus": AucNewCampusPageContent,
  "tmg-four-seasons": TmgFourSeasonsPageContent,
  "king-faisal-university-hospital": KingFaisalUniversityHospitalPageContent,
  "prince-mohamed-bin-fahd-medical-research": PrinceMohamedBinFahdMedicalResearchPageContent,
  "tabouk-hotel": TaboukHotelPageContent,
  "baha-hotel": BahaHotelPageContent,
  "labor-camp": LaborCampPageContent,
  "al-khafji-joint-operations-housing": AlKhafjiJointOperationsHousingPageContent,
  "king-faisal-university": KingFaisalUniversityPageContent,
  "qassim-university-hospital": QassimUniversityHospitalPageContent,
  "gotevt-headquarters": GotevtHeadquartersPageContent,
  "jubail-university-college": JubailUniversityCollegePageContent,
  "arriyadh-courts-complex": ArriyadhCourtsComplexPageContent,
  "wakf-al-madani-hotel": WakfAlMadaniHotelPageContent,
  "jubail-industrial-college": JubailIndustrialCollegePageContent,
  "egyptian-consulate-jeddah": EgyptianConsulateJeddahPageContent,
  "ebda-khaira": EbdaKhairaPageContent,
  "jeddah-wastewater-networks": JeddahWastewaterNetworksPageContent,
  "iskan-al-ahsa": IskanAlAhsaPageContent,
  "dubai-business-bay": DubaiBusinessBayPageContent,
  "ebb-university-yemen": EbbUniversityYemenPageContent,
  "lusail": LusailPageContent,
  "damam-water-tower": DamamWaterTowerPageContent,
} as const satisfies Record<string, ComponentType<{ project: Project }>>;
